[build]
  command = "make build"
  functions = "PVS_API/functions"
  publish = "PVS_API/public"

[build.environment]
  GO_IMPORT_PATH = "github.com/bymi15/PVS/PVS_API"
  GO111MODULE = "on"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200